### ISSUE TITLE
Error Launching Gama 1.8

### ISSUE THREAD

**Issue by Jarakoto** [ANRGenstar/genstar.gamaplugin#1]
#### Describe the bug

When you launch Gama 1.8, you get "Errors exist in required project(s): genstar.plugin.bundle-all".

#### To Reproduce
- Install Gama from [https://github.com/gama-platform/gama/wiki/InstallingGitVersion],
- follow instructions in README.MD and launch Gama.

#### Crash Log or System Log
If you proceed with launch you get this [log](https://github.com/ANRGenstar/genstar.gamaplugin/files/3393106/default.log).

#### Device Information
- Ubuntu 18.04.2 LTS
- Gama 1.8 (git version)

**Comment by chapuisk** [comment]
Hi,
The Gama git version is slowly moving toward the replacement of graphstream so the Genstar plugin should do the same ;) We are currently fixing the issue :  1) quick fix changing dependancies 2) get rid of graphstream to follow Gama path
Get you feedback when it is done

**Comment by Jarakoto** [comment]
Hi

**Comment by benoitgaudou** [comment]
I just tried this morning and was able to run the genstar on my Git GAMA.

**Comment by Jarakoto** [comment]
@chapuisk The issue is actually due to a missing dependency of graphstream in the gama plugin. Temporary quick fix by adding it manually.
