### ISSUE TITLE
Population generation from a detailed file (sample?)

### ISSUE THREAD

**Issue by rmejean** [ANRGenstar/genstar.gamaplugin#2]
Hi everyone,

I have a detailed file (one line = one person) from a population census and I want to use it to generate a synthetic population with GEN*.
I understand that `with_generation_algo "Sample"` allows that... but the GAML files provided as examples with the plugin (generator_sample_is.gaml and generator_sample.gaml) are empty. Is the functionality implemented in the plugin?

Thank you
Romain

**Comment by chapuisk** [comment]
Hi @rmejean ,

We still work to do on models to explain the possibilities. The idea of re-using a sample to generate a synthetic population of a given size is already possible with the current state of the plugin:
``my_pop_generator with_generation_algo  "simple_draw"`` 
Before that you'll have to register attributes and then you can use the sample

Best,
Kevin

**Comment by rmejean** [comment]
Thank you for your answer, @chapuisk. I successfully used my detail file (don't forget to define the type `"Sample"` with `add_census_file`) thanks to you.

However, the file I use represents the entire population and is not a sample. This is a file containing 2111 lines, so I ask GENSTAR to generate 2111 agents, but it always creates less, and the number of agents changes with each simulation: 1875, 1867, 1843, etc. This is normal, because I use this sample function, which should generate a population from a probability sample. But perhaps there is a way or should there be a way to use a complete population in GENSTAR?

Best regards,
Romain

**Comment by rmejean** [comment]
Re (small precision),

In my code, GENSTAR creates exactly the number of agents I ask it to create, but when I add these two lines, the number of agents created is not the same as the one indicated (slightly lower) and changes with each new simulation :

`hog_gen <- hog_gen localize_on_census (sectores_shp.path);`
`hog_gen <- hog_gen add_spatial_mapper (stringOfCensusIdInCSVfile, stringOfCensusIdInShapefile);`

**Comment by chapuisk** [comment]
Hi @rmejean,

When you use a (genstar) sampler to draw n entity from a data sample of your target population, you draw n records with a uniform probability. It means that you will have duplicates in your original unspatialized population. That's right ! But when you try to locate them using the exact mapping between CensusID and your sectors (this is what ``add_spatial_mapper`` is about) those who have the same CensusID (the duplicates) will be erase to let only one remain.

I am looking for a raw result sampler (which is possible in the Java lib) where it is an exact one agent for one entity of your sample. If there is none, I'll update the plugin so you can do so. Hence, it will make it possible to have 2111 agents from your 2111 lines data sample, no more no less. 

I'll post the fix and close the issue soon,

cheers,
Kevin

**Comment by chapuisk** [comment]
Re,

After a quick check it happens that if you create your population (let's say of people species) without any number facets (i.e. ``create people from:hog_gen``) it should return your exact raw sample; for that you'll have to specified the input "sample" file (as you mention) and use the ``simple_draw`` generator. If it works, plz comment and close the issue.

Edit: If it creates only one agent, try with a negative or null number facet options (e.g. number:-1)

Best,
Kevin

**Comment by rmejean** [comment]
Thank you for your help and for all this information, Kevin. Indeed, without any number facets, it works perfectly!

Best,
Romain

**Comment by rmejean** [comment]
> without any number facets, it works perfectly!

Actually, no! With no number facets, a bug occurs: my agents are no longer spatialized. The following lines of code no longer have any effect : 

`hog_gen <- hog_gen localize_on_census (sectores_shp.path);`
`hog_gen <- hog_gen add_spatial_mapper (stringOfCensusIdInCSVfile, stringOfCensusIdInShapefile);`
`hog_gen <- hog_gen localize_on_geometries (buildings_shp.path);`

With `create hogares from: hog_gen number: 2111;` agents are well located according to the census and the buildings layer, and with `create hogares from: hog_gen`, no.

Edit: I have tried with a negative or null number facet options.

Best,
Romain

**Comment by chapuisk** [comment]
Hi @rmejean ,
ok ! can you go deeper in the problem: where the spatialization failed ? either when it comes to "map" your agent with your sectors, or when it comes to bind them with a particular building. If your agents are uniformly localized (meaning mapping step 1 failed), can you look at your agents attributes, and namely if you have a CensusId variable well encoded for Gen* to bind synthetic entities with sectors. We have to identify the delta in your population of agent when you create them using the number facet and without it. After that I may be able to update the plugin.
Best,
Kevin

**Comment by rmejean** [comment]
Hi @chapuisk,

It seems to me that without any number facet, my agents are uniformly localized : neither step 1 nor step 2 is taken into account. Agents attributes are correct, since Gen* has no problem locating them with `number: 2111`...
If necessary, the code of my init with Gen* is available on my project (https://github.com/rmejean/nea-lucc-abm - line 108 of the file fonctionnel.gaml).

Thank you for your quick response, it's very nice!
Best,
Romain

**Comment by rmejean** [comment]
Re @chapuisk, 

I checked the attributes of my agents and tried with other files: same problem if I try to do the same thing in the file localize_on_iris_building.gaml, provided as an example.
I modified the generation algorithm to `simple_draw` and I delete the facet number: agents are no longer located on the buildings or according to the census.

Code & screenshot : 

```
global {
	file f_IRIS <- file("../../data/Rouen_sample_iris.csv"); //file changed for the sample
	file iris_shp <- file("../../data/shp/Rouen_iris_number.shp"); 

	file buildings_shp <- file("../../data/shp/buildings.shp");

	string stringOfCensusIdInShapefile <- "CODE_IRIS";

	string stringOfCensusIdInCSVfile <- "iris";
	
	int nb_personas -> length(people);




	geometry shape <- envelope(buildings_shp);

	init {		
		create building from: buildings_shp ;	
		create iris_agent from: iris_shp with: [code_iris::string(read('CODE_IRIS'))];			
		
		gen_population_generator pop_gen;
		pop_gen <- pop_gen with_generation_algo "simple_draw"; //change for simple draw method

		pop_gen <- add_census_file(pop_gen, f_IRIS.path, "Sample", ",", 1, 1);	//type : sample		
			
		// -------------------------
		// Setup "IRIS" attribute: INDIVIDUAL
		// -------------------------

		list<string> liste_iris <- [
			"765400602", "765400104","765400306","765400201",
			"765400601","765400901","765400302","765400604","765400304",
			"765400305","765400801","765400301","765401004","765401003",
			"765400402","765400603","765400303","765400103","765400504",
			"765401006","765400702","765400401","765400202","765400802",
			"765400502","765400106","765400701","765401005","765400204",
			"765401001","765400405","765400501","765400102","765400503",
			"765400404","765400105","765401002","765400902","765400403",
			"765400203","765400101","765400205"];

		pop_gen <- pop_gen add_attribute("iris", string, liste_iris,"P13_POP", int);
		
		// -------------------------
		// Spatialization 
		// -------------------------
		
		pop_gen <- pop_gen localize_on_geometries(buildings_shp.path);
		pop_gen <- pop_gen localize_on_census(iris_shp.path);
		pop_gen <- pop_gen add_spatial_mapper(stringOfCensusIdInCSVfile,stringOfCensusIdInShapefile);
		

		// -------------------------			
		create people from: pop_gen  ; //facet number deleted
	}
}
```
![image](https://user-images.githubusercontent.com/22102206/65878543-9c616300-e38e-11e9-87aa-2f99ea0b495c.png)

Best,
Romain

**Comment by chapuisk** [comment]
Hey @rmejean ,
So this is definitely something related with the use of raw sample. I will have a look asap and I'll get back to you quickly !
Best,
Kevin

**Comment by chapuisk** [comment]
Hi @rmejean ,
There were a little bug when using raw sample that exit the generation before the localization process. It should work now (at least for the git version of the plugin). I also update the example model you mentioned, with sample based or sample free generation and localization process.
Best,
Kevin

**Comment by rmejean** [comment]
Hi @chapuisk,
Thank you very much for these corrections, it works perfectly! Thank you also for updating the examples.
I think it just lacks `import java.util.Arrays;` at the beginning of the genstar.gamaplugin/src/genstar/gamaplugin/utils/GenStarGamaUtils.java file, because there was a small error.

Best,
Romain
