### ISSUE TITLE
Nesting process: about relaxing constraints

### ISSUE THREAD

**Issue by rmejean** [ANRGenstar/genstar.gamaplugin#6]
Hi,

I read in @ptaillandier's habilitation thesis that several types of constraints could be chosen to drive the nesting process: geometric constraint, contingency constraint and density constraint. All this echoes the features recently added by @chapuisk (issue#4).

I also read that it is possible to first relax one constraint before another (e. g. first relax the geometric constraint before the contingency constraint). This is what I am trying to do: I would like GEN* to **absolutely maintain my contingency constraint** (set at 1 agent max per object, never more) but to be more flexible on the geometric constraint (when no nest is available in the required administrative unit, look for a nest in the other administrative units)

Do you know how I could do that? Is this possible with the GAMA plugin?

Thank you in advance for your answers.

Best regards,
Romain Mejean

**Comment by chapuisk** [comment]
Hi @rmejean 

I update the ``add_capacity_distribution`` and ``add_density_distribution`` operator ! Now there have a third argument which is the limit up to which constraint can be relaxed. If you set it to 1 they will be no more than 1 agent per nest / per m square in nest respectively. However, you'll have to test it extensively (at least there is no error ;).

Considering the second answer, I am not sure and I need more time to investigate the API. I'll get back to you as soon as I got time to do so.

Best,
Kevin

**Comment by rmejean** [comment]
Hi @chapuisk,

I tested the functionality: it works (there are no errors when launching) but it seems to me that the expected effect is missing: GEN* locates several agents on the same object despite my `add_capacity_distribution (1,1)`.
Example on the attached screenshot: my agents (small circles) are sometimes several on the same plot (rectangles).

![Capture](https://user-images.githubusercontent.com/22102206/68875338-f3cf4e80-0702-11ea-9492-e1adf2b3081d.PNG)

For the second question (relax one constraint before another), very well, thank you for your answer and your help! :)

Best,
Romain

**Comment by chapuisk** [comment]
Hi @rmejean ,
I ve gone into deep changes from API to the plugin, with a clarification on several concepts and operators: 

1. Concepts : now you have ``add_spatial_match`` (former mapper) when you want to match synthetic entities and geometries, e.g. people and census area. I also make a clear distinction between distribution (which give a probability of being associated to each "_nest_") and constraint (which filters "_nest_" to be either acceptable or not). 
2. Operators : ``add_capacity_constraint`` allows you to define a strict constraint on capacity of nest. Every constraint is associated with a priority, a maximum value and step value increase when released.

If you need more on those point, go PM ;)

I let you close the issue if it's ok for you !

Best,
Kevin

**Comment by rmejean** [comment]
Hi @chapuisk,

Thank you for this work and explanations, all right, I close the issue!

Best,
Romain
